### ISSUE TITLE
The question consult

### ISSUE THREAD

**Issue by yaolp123** [johli/splirent#1]
Dear github authors:
  Recently I read your work called splient, and i am interested, alougth I have not konwn the genearal function of this project, and i try to read your project, and in splirent_data_5ss.py file, a5ss_splice_logic_library_mapped.csv and a5ss_splice_logic_counts.mat I could not find ,and I will keep understanding your perfect work, have a good day.
I am looking forward to your reply.
Best regards.

**Comment by johli** [comment]
Sorry for the late response. The "a5ss_splice_logic" data is an old artifact that is not used in the final version of the scripts, (in the training code at https://github.com/johli/splirent/blob/master/splirent/trainer/splirent_trainer.py it's turned off by default; 'targeted_a5ss_file_path = None').

Best,

Johannes
